
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.ColorButton textColourBtn;

	private global::Gtk.Label label5;

	private global::Gtk.ColorButton urgentColourBtn;

	private global::Gtk.Label label4;

	private global::Gtk.ColorButton focusedColourBtn;

	private global::Gtk.FontButton fontSelector;

	private global::Gtk.ComboBox generateTypeBtn;

	private global::Gtk.Button generateBtn;

	private global::Gtk.Label label3;

	private global::Gtk.ColorButton neutralColourBtn;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView configText;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button button9;

	private global::Gtk.Button testBtn;

	private global::Gtk.Button applyBtn;

	private global::Gtk.Label GtkLabel5;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.vbox4.BorderWidth = ((uint)(6));
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.fixed3.Add(this.label1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label1]));
		w3.X = 36;
		w3.Y = 25;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Text");
		this.fixed3.Add(this.label2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label2]));
		w4.X = 11;
		w4.Y = 17;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textColourBtn = new global::Gtk.ColorButton();
		this.textColourBtn.CanFocus = true;
		this.textColourBtn.Events = ((global::Gdk.EventMask)(784));
		this.textColourBtn.Name = "textColourBtn";
		this.fixed3.Add(this.textColourBtn);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textColourBtn]));
		w5.X = 7;
		w5.Y = 48;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Urgent");
		this.fixed3.Add(this.label5);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label5]));
		w6.X = 835;
		w6.Y = 13;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.urgentColourBtn = new global::Gtk.ColorButton();
		this.urgentColourBtn.CanFocus = true;
		this.urgentColourBtn.Events = ((global::Gdk.EventMask)(784));
		this.urgentColourBtn.Name = "urgentColourBtn";
		this.fixed3.Add(this.urgentColourBtn);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.urgentColourBtn]));
		w7.X = 839;
		w7.Y = 43;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Focused");
		this.fixed3.Add(this.label4);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label4]));
		w8.X = 724;
		w8.Y = 11;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.focusedColourBtn = new global::Gtk.ColorButton();
		this.focusedColourBtn.CanFocus = true;
		this.focusedColourBtn.Events = ((global::Gdk.EventMask)(784));
		this.focusedColourBtn.Name = "focusedColourBtn";
		this.fixed3.Add(this.focusedColourBtn);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.focusedColourBtn]));
		w9.X = 731;
		w9.Y = 45;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.fontSelector = new global::Gtk.FontButton();
		this.fontSelector.CanFocus = true;
		this.fontSelector.Name = "fontSelector";
		this.fontSelector.FontName = "Times New Roman, 26";
		this.fixed3.Add(this.fontSelector);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.fontSelector]));
		w10.X = 77;
		w10.Y = 49;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.generateTypeBtn = global::Gtk.ComboBox.NewText();
		this.generateTypeBtn.AppendText(global::Mono.Unix.Catalog.GetString("Harmonious"));
		this.generateTypeBtn.AppendText(global::Mono.Unix.Catalog.GetString("Tonal"));
		this.generateTypeBtn.AppendText(global::Mono.Unix.Catalog.GetString("Complementary"));
		this.generateTypeBtn.Name = "generateTypeBtn";
		this.generateTypeBtn.Active = 0;
		this.fixed3.Add(this.generateTypeBtn);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.generateTypeBtn]));
		w11.X = 525;
		w11.Y = 3;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.generateBtn = new global::Gtk.Button();
		this.generateBtn.CanFocus = true;
		this.generateBtn.Name = "generateBtn";
		this.generateBtn.UseUnderline = true;
		this.generateBtn.Label = global::Mono.Unix.Catalog.GetString("Generate");
		this.fixed3.Add(this.generateBtn);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.generateBtn]));
		w12.X = 559;
		w12.Y = 45;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Neutral");
		this.fixed3.Add(this.label3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label3]));
		w13.X = 428;
		w13.Y = 8;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.neutralColourBtn = new global::Gtk.ColorButton();
		this.neutralColourBtn.CanFocus = true;
		this.neutralColourBtn.Events = ((global::Gdk.EventMask)(784));
		this.neutralColourBtn.Name = "neutralColourBtn";
		this.fixed3.Add(this.neutralColourBtn);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.neutralColourBtn]));
		w14.X = 431;
		w14.Y = 40;
		this.vbox4.Add(this.fixed3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.fixed3]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		w15.Padding = ((uint)(20));
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.configText = new global::Gtk.TextView();
		this.configText.CanFocus = true;
		this.configText.Name = "configText";
		this.configText.Editable = false;
		this.configText.LeftMargin = 5;
		this.configText.RightMargin = 5;
		this.GtkScrolledWindow.Add(this.configText);
		this.vbox4.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
		w17.Position = 2;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Homogeneous = true;
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("Import");
		this.hbox2.Add(this.button9);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button9]));
		w18.Position = 0;
		w18.Padding = ((uint)(10));
		// Container child hbox2.Gtk.Box+BoxChild
		this.testBtn = new global::Gtk.Button();
		this.testBtn.CanFocus = true;
		this.testBtn.Name = "testBtn";
		this.testBtn.UseUnderline = true;
		this.testBtn.Label = global::Mono.Unix.Catalog.GetString("Test");
		this.hbox2.Add(this.testBtn);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.testBtn]));
		w19.Position = 1;
		w19.Padding = ((uint)(10));
		// Container child hbox2.Gtk.Box+BoxChild
		this.applyBtn = new global::Gtk.Button();
		this.applyBtn.CanFocus = true;
		this.applyBtn.Name = "applyBtn";
		this.applyBtn.UseUnderline = true;
		this.applyBtn.Label = global::Mono.Unix.Catalog.GetString("Apply");
		this.hbox2.Add(this.applyBtn);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.applyBtn]));
		w20.Position = 2;
		w20.Padding = ((uint)(10));
		this.vbox4.Add(this.hbox2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
		w21.PackType = ((global::Gtk.PackType)(1));
		w21.Position = 3;
		w21.Expand = false;
		w21.Fill = false;
		w21.Padding = ((uint)(10));
		this.GtkAlignment.Add(this.vbox4);
		this.frame3.Add(this.GtkAlignment);
		this.GtkLabel5 = new global::Gtk.Label();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.Xalign = 0F;
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Styling</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel5;
		this.Add(this.frame3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 939;
		this.DefaultHeight = 738;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.textColourBtn.ColorSet += new global::System.EventHandler(this.textColourSet);
		this.urgentColourBtn.ColorSet += new global::System.EventHandler(this.urgentColourSet);
		this.focusedColourBtn.ColorSet += new global::System.EventHandler(this.focusedColourSet);
		this.fontSelector.FontSet += new global::System.EventHandler(this.onChange);
		this.generateBtn.Clicked += new global::System.EventHandler(this.generateClicked);
		this.neutralColourBtn.ColorSet += new global::System.EventHandler(this.NeutralClicked);
		this.button9.Clicked += new global::System.EventHandler(this.onClick);
		this.testBtn.Clicked += new global::System.EventHandler(this.testClicked);
		this.applyBtn.Clicked += new global::System.EventHandler(this.applyClicked);
	}
}
